config/routes.rb
Atoolkit2::Application.routes.draw do
	
  resources :items do 
	collection do
		get :search
		post :search
	end
	resources :values
  end
  
  resources :properties do 
	resources :values
  end
  
  resources :values do 
	collection do 
		get :filters
		post :filters
	end
  end

end

app/models/property.rb
class Property < ActiveRecord::Base
	has_many :values, :dependent => :destroy
	has_many :items, :through => :values
	
	attr_accessible :name
	
	after_save { |property| property.destroy if property.name.blank? }
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.json
  
  require 'will_paginate/array'
  
  def index
    @properties = Property.all.uniq.paginate(:per_page => 50, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @properties.to_json(:only => [:id,:name])}
    end
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @property = Property.find(params[:id])
    @build_json = {:id => @property.id, :property => @property.name, :items => @property.items.collect{|item| [item.id, item.values.where(:property_id => @property.id)]}}
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @build_json.to_json(:only => [:id, :property, :items, :name])}
    end
  end

  # GET /properties/new
  # GET /properties/new.json
  def new
    @property = Property.new
    @build_json = {:id => @property.id, :property => @property.name, :items => @property.items.collect{|item| [item.id, item.values.where(:property_id => @property.id)]}}
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @build_json }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(params[:property])
    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { head :ok }
      else
        format.html { render action: "new" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.json
  def update
    @property = Property.find(params[:id])
    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url }
      format.json { head :ok }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.name %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @property.name %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>